# Nixpacks configuration for Railway
[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["echo 'Build completed - Server ready'"]

[start]
cmd = "node server/server.js"

[variables]
NODE_ENV = "production"